### ISSUE TITLE
Using ENC we are getting an error

### ISSUE THREAD

**Issue by artak116** [garethr/garethr-docker#379]
Dear Garethr,

When using ENC we get an error with the following yaml file .

---
  classes:
    - docker::run_instance

  docker::run_instance::instance:
    helloworld:
      image: 'tomcat8'

Error is : Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Must pass instance to Class[Docker::Run_instance] on node .

Any suggestions why thist doesn't work.

Thank You

**Comment by zahaim** [comment]
Hi,

Do you use spaces as it is supposed to be in yaml files? Please check yaml.org
The following code works fine for me:

````yaml
---
classes:
  - docker::run_instance

docker::run_instance::instance:
  'image_name':
    image: 'podbox/tomcat8'
````

If you do not have 'tomcat8' image locally please use 'tomcat' or some other existing tomcat image (like podbox).

Hope that helped.
